### ISSUE TITLE
BlockingIOError when running on Python 3.6

### ISSUE THREAD

**Issue by gmasonxoom** [pycontribs/tendo#78]
Hi,

When attempting to implement tendo to make a simple Python script a singleton, the following blocking error occurs. Not sure of the cause, any help very welcomed.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tendo/singleton.py", line 64, in __init__
    fcntl.lockf(self.fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/fs_api_cron/cron.py", line 10, in <module>
    me = singleton.SingleInstance() # will sys.exit(-1) if other instance is running
  File "/usr/local/lib/python3.6/site-packages/tendo/singleton.py", line 68, in __init__
    raise SingleInstanceException()
tendo.singleton.SingleInstanceException```

**Comment by ssbarnea** [comment]
Sorry but py36 is EOL so I would not do anything about it.
